### ISSUE TITLE
 dependency not listed in CKAN

### ISSUE THREAD

**Issue by GrayTechGH** [linuxgurugamer/WaypointManager#8]
For WaypointManager 2.8.3 SpaceTuxLibrary is not listed as a dependancy in CKAN.

**Comment by Darael** [comment]
Since I'm passing by: This is fixed in KSP-CKAN/NetKAN#8616, which was merged two hours ago, and the change shows up in my CKAN accordingly.

**Comment by linuxgurugamer** [comment]
Well, yes, I did that merge :-)
